name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        jdk: [3-openjdk-17-slim, 3-jdk-14, 3-jdk-8-slim]
        influxdb: ['1.1', '1.6', '1.8', '2.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build project
        env:
          MAVEN_JAVA_VERSION: "${{ matrix.jdk }}"
          INFLUXDB_VERSION: "${{ matrix.influxdb }}"
        run: ./compile-and-test.sh

      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)


  # deploy:
  #   runs-on: ubuntu-20.04

  #   steps:
  #     - name: deploy snapshot
  #       env:
  #         secure: dAJK41xM2dN3q3xJMqAOP6uvrOvpjjUzmHr8mYNyepER8Lpms9/GqVUxqJv12wzCBqv1XZk/CXxrv3iBc2XjlxlrzIJGQChTinwDEigv0BMl/Gh0821ja7gwzMEUmg9f79m5tJxIFQ306cWz1gyRDqM3fLzskvM2ayzvynsNc/w=
  #       run: ./deploy-snapshot.sh
