name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        jdk: [3-jdk-14]
        influxdb: [1.8]
#        jdk: [3-jdk-14, 3-jdk-8-slim]
#        influxdb: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build project
        env:
          MAVEN_JAVA_VERSION: ${{ matrix.jdk }}
          INFLUXDB_VERSION: ${{ matrix.influxdb }}
        run: ./compile-and-test.sh

      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)
