name: Build from pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        jdk: [3-openjdk-16-slim, 3-jdk-14, 3-jdk-8-slim]
        influxdb: ['1.1', '1.6', '1.8', '2.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Figure out if running fork PR
        id: fork
        run: '["${{ secrets.DOCKER_REGISTRY_TOKEN }}" == ""] && echo "::set-output name=is_fork_pr::true" || echo "::set-output name=is_fork_pr::false"'

      - name: Build project
        env:
          MAVEN_JAVA_VERSION: "${{ matrix.jdk }}"
          INFLUXDB_VERSION: "${{ matrix.influxdb }}"
        run: ./compile-and-test.sh

      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)
        if: matrix.influxdb != '2.0'
